### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [digitapex/DerDieDas#1]
Could you please specify what license your app is covered by? Thanks!

**Comment by IzzySoft** [comment]
@digitapex any chance?

**Comment by IzzySoft** [comment]
@digitapex not even a short statement on the issue? I've no idea what the problem is with chosing a license. If you stated, the community might be able to help.

**Comment by IzzySoft** [comment]
Well, if you cannot decide, do you need suggestions?

**Comment by digitapex** [comment]
I have added a license.

**Comment by machiav3lli** [comment]
Great, thanks.

**Comment by IzzySoft** [comment]
Yes, thanks a lot!
